### PR TITLE
fixed typo in filename

### PR DESCRIPTION
**Pull request by paulrouge**

### CODE REVIEW

**Comment by han-so1omon** [comment]
@paulrouge Of course, we always appreciate a new pull request. However, I'm not sure this is the right approach. Can you please provide more context and tests to prove that this code is unreachable?

Additionally, please be sure to show that any updates to file names do not cause errors in the import statements from other pieces of code that use this file

Otherwise, these small changes may cause larger issues

Thanks!

**Comment by paulrouge** [comment]
Hi @han-so1omon, 

In go the filename does not matter for import, rather the package name the file has and the folder where it's located.

On the removed 'return' statement in func NewLink() ,  all conditionals are handled correctly, so the last 'return' will never be reached.

So the two changes won't cause any issues. That being said, not commiting these changes won't change anything either!

**Comment by han-so1omon** [comment]
Changing the file name looks ok. The `return nil` statement should remain, as this is protection for future usage cases of that function

**Comment by paulrouge** [comment]
I see, that makes sense!

**Pull request closed without merging**
